
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ramco
 */
public class FikstürTablosu extends javax.swing.JFrame {

    /**
     * Creates new form FikstürTablosu
     */
    Maçlar fikstürt = new Maçlar();
    public FikstürTablosu() {
        initComponents();
         fikstürt.fillFikstürTablosu(FikstürTablosu, "");
         
        FikstürTablosu.setRowHeight(30);
        FikstürTablosu.setShowGrid(true);
        FikstürTablosu.setGridColor(Color.pink);
        FikstürTablosu.setSelectionBackground(Color.DARK_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FikstürPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FikstürTablosu = new javax.swing.JTable();
        buton_ekle_FT = new javax.swing.JButton();
        buton_güncelle_FT = new javax.swing.JButton();
        buton_sil_FT = new javax.swing.JButton();
        textf_arama_FT = new javax.swing.JTextField();
        tablo_label_FT = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        güncelle_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textf_maçid_FT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        label_evsahibi_FT = new javax.swing.JTextField();
        label_ligadı_FT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sp_evsahibiskor_FT = new javax.swing.JSpinner();
        sp_deplasmanskor_FT = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        label_deplasman_FT = new javax.swing.JTextField();
        tarih_FT = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FikstürPanel.setBackground(new java.awt.Color(255, 217, 175));

        FikstürTablosu.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        FikstürTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "maç_id", "lig adı", "ev sahibi", "deplasman", "maç tarihi", "ev sahibi skoru", "deplasman skoru"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FikstürTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FikstürTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(FikstürTablosu);

        buton_ekle_FT.setText("Maç Ekle");
        buton_ekle_FT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_ekle_FTActionPerformed(evt);
            }
        });

        buton_güncelle_FT.setText("Güncelle");
        buton_güncelle_FT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_güncelle_FTActionPerformed(evt);
            }
        });

        buton_sil_FT.setText("Sil");
        buton_sil_FT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_sil_FTActionPerformed(evt);
            }
        });

        textf_arama_FT.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        textf_arama_FT.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), java.awt.Color.darkGray));
        textf_arama_FT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textf_arama_FTActionPerformed(evt);
            }
        });
        textf_arama_FT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textf_arama_FTKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textf_arama_FTKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textf_arama_FTKeyTyped(evt);
            }
        });

        tablo_label_FT.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        tablo_label_FT.setText("FİKSTÜR TABLOSU");
        tablo_label_FT.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 102), new java.awt.Color(204, 0, 0), null, new java.awt.Color(153, 0, 102)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 3)));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel11.setText("Aramak istediğiniz takımı girin :");

        güncelle_panel.setBackground(new java.awt.Color(255, 217, 175));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel2.setText("Deplasman takım :");

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel9.setText("Maç Id :");

        textf_maçid_FT.setEditable(false);
        textf_maçid_FT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textf_maçid_FTActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel3.setText("Maç tarihi :");

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel12.setText("Ev Sahibi Takım :");

        label_evsahibi_FT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_evsahibi_FTActionPerformed(evt);
            }
        });

        label_ligadı_FT.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel4.setText("Ev Sahibi Skor :");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel5.setText("Deplasman Skor :");

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel1.setText("Lig Adı : ");

        tarih_FT.setBackground(new java.awt.Color(204, 255, 204));
        tarih_FT.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout güncelle_panelLayout = new javax.swing.GroupLayout(güncelle_panel);
        güncelle_panel.setLayout(güncelle_panelLayout);
        güncelle_panelLayout.setHorizontalGroup(
            güncelle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, güncelle_panelLayout.createSequentialGroup()
                .addGroup(güncelle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(güncelle_panelLayout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addGroup(güncelle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, güncelle_panelLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(güncelle_panelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(güncelle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(güncelle_panelLayout.createSequentialGroup()
                                        .addGroup(güncelle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26))
                                    .addGroup(güncelle_panelLayout.createSequentialGroup()
                                        .addGroup(güncelle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)))))
                        .addGroup(güncelle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(güncelle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label_ligadı_FT)
                                .addComponent(textf_maçid_FT, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tarih_FT, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_evsahibi_FT, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_deplasman_FT, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(güncelle_panelLayout.createSequentialGroup()
                        .addGroup(güncelle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(50, 50, 50)
                        .addGroup(güncelle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sp_deplasmanskor_FT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_evsahibiskor_FT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        güncelle_panelLayout.setVerticalGroup(
            güncelle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(güncelle_panelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(güncelle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textf_maçid_FT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(güncelle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_ligadı_FT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(güncelle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(label_evsahibi_FT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(güncelle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_deplasman_FT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(güncelle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tarih_FT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(güncelle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_evsahibiskor_FT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(güncelle_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_deplasmanskor_FT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FikstürPanelLayout = new javax.swing.GroupLayout(FikstürPanel);
        FikstürPanel.setLayout(FikstürPanelLayout);
        FikstürPanelLayout.setHorizontalGroup(
            FikstürPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FikstürPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(FikstürPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(güncelle_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tablo_label_FT))
                .addGroup(FikstürPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FikstürPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textf_arama_FT, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FikstürPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(FikstürPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(buton_güncelle_FT, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171)
                .addComponent(buton_ekle_FT, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buton_sil_FT, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        FikstürPanelLayout.setVerticalGroup(
            FikstürPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FikstürPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(FikstürPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tablo_label_FT, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(textf_arama_FT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FikstürPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(güncelle_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(FikstürPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buton_güncelle_FT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_ekle_FT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_sil_FT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FikstürPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FikstürPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FikstürTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FikstürTablosuMouseClicked
        int rowIndex = FikstürTablosu.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)FikstürTablosu.getModel();

        textf_maçid_FT.setText(model.getValueAt(rowIndex, 0).toString());
        label_ligadı_FT.setText(model.getValueAt(rowIndex, 1).toString());
        label_evsahibi_FT.setText(model.getValueAt(rowIndex, 2).toString());
        label_deplasman_FT.setText(model.getValueAt(rowIndex, 3).toString());
        Date maçTarih;
        try {
            maçTarih = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
            tarih_FT.setDate(maçTarih);
        
        } catch (ParseException ex) {
            Logger.getLogger(FikstürTablosu.class.getName()).log(Level.SEVERE, null, ex);
        }
        sp_evsahibiskor_FT.setValue(model.getValueAt(rowIndex, 5));
        sp_deplasmanskor_FT.setValue(model.getValueAt(rowIndex, 6));
        

    }//GEN-LAST:event_FikstürTablosuMouseClicked

    private void buton_ekle_FTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_ekle_FTActionPerformed
        MaçEkle macekle = new MaçEkle();
        macekle.setVisible(true);
        macekle.pack();
        macekle.setLocationRelativeTo(null);
        macekle.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //takım ekleme sayfası kapatıldığında ana ekranın hala açık kalmasını sağlar
    }//GEN-LAST:event_buton_ekle_FTActionPerformed

    
    public boolean Kontrol(){
        //boşluk kontrolü
        if (label_ligadı_FT.getText().equals("") || (label_evsahibi_FT).getText().equals("") ||
                (label_deplasman_FT).getText().equals("") || tarih_FT.getDate() == null){
            JOptionPane.showMessageDialog(null, "boş alan bırakmayınız!");
            return false;
        }
        //spinnera girilen sayılar - olamaz
        else if ((Integer) sp_evsahibiskor_FT.getValue() < 0 || (Integer) sp_deplasmanskor_FT.getValue() < 0){
            JOptionPane.showMessageDialog(null, "skorlar sıfırdan küçük olamaz!");
            return false;
        }
        else
            return true;
    }
    
    private void buton_güncelle_FTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_güncelle_FTActionPerformed
        int id = Integer.valueOf(textf_maçid_FT.getText()); //textfieldden aldığımız için sonrasında inte dönüştürdük
        String ligAdı = label_ligadı_FT.getText();
        String ev_sahibi = label_evsahibi_FT.getText();
        String deplasman = label_deplasman_FT.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String maçTarih = dateFormat.format(tarih_FT.getDate());
        int ev_sahibi_skor =(Integer) sp_evsahibiskor_FT.getValue();
        int deplasman_skor =(Integer) sp_deplasmanskor_FT.getValue();
        int lig_id = 0;

      

        if (Kontrol()){
            //güncelleme yapılmasını sağlar
            fikstürt.EkleGüncelleSilTakım('g', id, ligAdı, ev_sahibi, deplasman, 
                    maçTarih, ev_sahibi_skor, deplasman_skor); //puanlar sınıfındaki ilgili metoda giderek güncelleme yapmayı sağlar.
        }
        //eski tablodan bir tane daha eklemek yerine üstüne ekler
        FikstürTablosu.setModel(new DefaultTableModel(null, new Object[] {"maç_id", "lig adı", "ev sahibi", "deplasman", "maç tarihi", "ev sahibi skoru", "deplasman skoru"}));
        fikstürt.fillFikstürTablosu(FikstürTablosu, "");
    }//GEN-LAST:event_buton_güncelle_FTActionPerformed

    private void buton_sil_FTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_sil_FTActionPerformed
        int id = Integer.valueOf(textf_maçid_FT.getText());
        fikstürt.EkleGüncelleSilTakım('s', id, null, null, null, null, null, null);

        FikstürTablosu.setModel(new DefaultTableModel(null, new Object[] {"maç_id", "lig adı", "ev sahibi", "deplasman", "maç tarihi", "ev sahibi skoru", "deplasman skoru"}));
        fikstürt.fillFikstürTablosu(FikstürTablosu, "");

        //seçilen satır silindikten sonra sol ekranda bilgileri de silinsin
        textf_maçid_FT.setText("");
        label_ligadı_FT.setText("");
        label_evsahibi_FT.setText("");
        label_deplasman_FT.setText("");
        tarih_FT.setDate(null);
        sp_evsahibiskor_FT.setValue(0);
        sp_deplasmanskor_FT.setValue(0);
        
    }//GEN-LAST:event_buton_sil_FTActionPerformed

    private void textf_arama_FTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textf_arama_FTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textf_arama_FTActionPerformed

    private void textf_arama_FTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textf_arama_FTKeyPressed

    }//GEN-LAST:event_textf_arama_FTKeyPressed

    private void textf_arama_FTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textf_arama_FTKeyReleased
        FikstürTablosu.setModel(new DefaultTableModel(null, new Object[] {"maç_id", "lig adı", "ev sahibi", "deplasman", "maç tarihi", "ev sahibi skoru", "deplasman skoru"}));
        fikstürt.fillFikstürTablosu(FikstürTablosu, textf_arama_FT.getText());
    }//GEN-LAST:event_textf_arama_FTKeyReleased

    private void textf_arama_FTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textf_arama_FTKeyTyped

    }//GEN-LAST:event_textf_arama_FTKeyTyped

    private void textf_maçid_FTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textf_maçid_FTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textf_maçid_FTActionPerformed

    private void label_evsahibi_FTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_evsahibi_FTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_evsahibi_FTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FikstürTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FikstürTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FikstürTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FikstürTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FikstürTablosu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FikstürPanel;
    public static javax.swing.JTable FikstürTablosu;
    private javax.swing.JButton buton_ekle_FT;
    private javax.swing.JButton buton_güncelle_FT;
    private javax.swing.JButton buton_sil_FT;
    private javax.swing.JPanel güncelle_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField label_deplasman_FT;
    private javax.swing.JTextField label_evsahibi_FT;
    private javax.swing.JTextField label_ligadı_FT;
    private javax.swing.JSpinner sp_deplasmanskor_FT;
    private javax.swing.JSpinner sp_evsahibiskor_FT;
    private javax.swing.JLabel tablo_label_FT;
    private com.toedter.calendar.JDateChooser tarih_FT;
    private javax.swing.JTextField textf_arama_FT;
    private javax.swing.JTextField textf_maçid_FT;
    // End of variables declaration//GEN-END:variables
}
