import java.sql.Connection;
import javax.swing.JTable;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.RowFilter.Entry;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ramco
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */

    public MainForm() {
        initComponents();
        displayMessage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cb_SporDalı = new javax.swing.JComboBox<>();
        cb_Ligler = new javax.swing.JComboBox<>();
        buton_puantablosugöster = new javax.swing.JButton();
        buton_temizle = new javax.swing.JButton();
        buton_çıkış = new javax.swing.JButton();
        buton_fikstürtablosugöster = new javax.swing.JButton();
        CardLayoutPanel = new javax.swing.JPanel();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 153));
        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 108, 2));
        jLabel1.setText("SPOR MÜSABAKASI ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setBackground(new java.awt.Color(255, 255, 153));
        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 108, 2));
        jLabel2.setText("TAKİP SİSTEMİ");

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        jLabel4.setText("LİGLER");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        jLabel5.setText("SPOR DALLARI");

        cb_SporDalı.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FUTBOL", "BASKETBOL", "VOLEYBOL"}));
        cb_SporDalı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_SporDalıActionPerformed(evt);
            }
        });

        cb_Ligler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_LiglerActionPerformed(evt);
            }
        });

        buton_puantablosugöster.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        buton_puantablosugöster.setText("PUAN TABLOSU GÖSTER");
        buton_puantablosugöster.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        buton_puantablosugöster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_puantablosugösterActionPerformed(evt);
            }
        });

        buton_temizle.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        buton_temizle.setText("TEMİZLE");
        buton_temizle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 2));
        buton_temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_temizleActionPerformed(evt);
            }
        });

        buton_çıkış.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        buton_çıkış.setForeground(new java.awt.Color(204, 0, 51));
        buton_çıkış.setText("ÇIKIŞ YAP");
        buton_çıkış.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_çıkışActionPerformed(evt);
            }
        });

        buton_fikstürtablosugöster.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        buton_fikstürtablosugöster.setText("FİKSTÜR GÖSTER");
        buton_fikstürtablosugöster.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));
        buton_fikstürtablosugöster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_fikstürtablosugösterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cb_Ligler, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_SporDalı, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buton_temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buton_puantablosugöster, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buton_fikstürtablosugöster, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buton_çıkış, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb_SporDalı, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_Ligler, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(buton_temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buton_puantablosugöster, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(buton_fikstürtablosugöster, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(buton_çıkış, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        CardLayoutPanel.setBackground(new java.awt.Color(205, 242, 206));

        javax.swing.GroupLayout CardLayoutPanelLayout = new javax.swing.GroupLayout(CardLayoutPanel);
        CardLayoutPanel.setLayout(CardLayoutPanelLayout);
        CardLayoutPanelLayout.setHorizontalGroup(
            CardLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1132, Short.MAX_VALUE)
        );
        CardLayoutPanelLayout.setVerticalGroup(
            CardLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CardLayoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CardLayoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_LiglerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_LiglerActionPerformed
    //System.out.println("cb_LiglerActionPerformed is under attack!!"); //her şey kontrolüm altında
   
      
    }//GEN-LAST:event_cb_LiglerActionPerformed



    private void buton_çıkışActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_çıkışActionPerformed
        this.dispose(); //bulunulan sayfadan çıkış yapılır
        login lg = new login(); //mainform sayfası açılır
            lg.setVisible(true);
            dispose();
            lg.pack();
            lg.setLocationRelativeTo(null);
    }//GEN-LAST:event_buton_çıkışActionPerformed

    private void buton_temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_temizleActionPerformed
        cb_SporDalı.setSelectedIndex(0);
        cb_Ligler.setSelectedIndex(0);
    }//GEN-LAST:event_buton_temizleActionPerformed

    private void cb_SporDalıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_SporDalıActionPerformed
        updateLiglerComboBox();
    }//GEN-LAST:event_cb_SporDalıActionPerformed

    private void buton_puantablosugösterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_puantablosugösterActionPerformed
        PuanTablosu pt= new PuanTablosu(); //puan tablosu sayfası gelir
        pt.setVisible(true);
        pt.pack();
        pt.setLocationRelativeTo(CardLayoutPanel);
        pt.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
    }//GEN-LAST:event_buton_puantablosugösterActionPerformed

    private void buton_fikstürtablosugösterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_fikstürtablosugösterActionPerformed
        FikstürTablosu pt = new FikstürTablosu(); //fikstür tablosu sayfası gelir
        pt.setVisible(true);
        pt.pack();
        pt.setLocationRelativeTo(CardLayoutPanel);
        pt.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
    }//GEN-LAST:event_buton_fikstürtablosugösterActionPerformed
    
    private void updateLiglerComboBox() {
    String selectedSporDalı = (String) cb_SporDalı.getSelectedItem();
    
    if (selectedSporDalı != null) {
        ArrayList<String> liglerList = new ArrayList<>();

        switch (selectedSporDalı) {
            case "FUTBOL":
                liglerList.add("SÜPER LİG");
                liglerList.add("PREMİER LİG");
                liglerList.add("LA LİGA");
                break;
            case "BASKETBOL":
                liglerList.add("TÜRKİYE SİGORTA BSL");
                liglerList.add("ING KADINLAR BSL");
                liglerList.add("NBA");
                break;
            case "VOLEYBOL":
                liglerList.add("SULTANLAR LİGİ");
                liglerList.add("AXA SİGORTA EFELER LİGİ");
                liglerList.add("AXA SİGORTA KUPA VOLEY");
                break;
            default:
                break;
        }

        cb_Ligler.setModel(new javax.swing.DefaultComboBoxModel<>(liglerList.toArray(new String[0])));
    }
    
    
    

}

    public void displayMessage() {
        System.out.println("main sınıf oynatıldı.");
    }
    
    //overloaded method
    public void displayMessage(String message) {
        System.out.println(message);
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardLayoutPanel;
    private javax.swing.JButton buton_fikstürtablosugöster;
    private javax.swing.JButton buton_puantablosugöster;
    private javax.swing.JButton buton_temizle;
    private javax.swing.JButton buton_çıkış;
    private javax.swing.JComboBox<String> cb_Ligler;
    private javax.swing.JComboBox<String> cb_SporDalı;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    // End of variables declaration//GEN-END:variables

   
}
