
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


public class PuanTablosu extends javax.swing.JFrame {

    /**
     * Creates new form PuanTablosu
     */
    
    Puanlar puant = new Puanlar();
        
    public PuanTablosu() {
        
        initComponents();
        
        puant.fillPuanTablosu(PuanTablosu, ""); //puan tablosu özelliklerini girdim
        
        PuanTablosu.setRowHeight(30);
        PuanTablosu.setShowGrid(true);
        PuanTablosu.setGridColor(Color.green);
        PuanTablosu.setSelectionBackground(Color.DARK_GRAY);

        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puanTablosuPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PuanTablosu = new javax.swing.JTable();
        buton_ekle = new javax.swing.JButton();
        buton_güncelle = new javax.swing.JButton();
        buton_sil = new javax.swing.JButton();
        tablo_label = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_takımadı_PT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sp_oynanan_PT = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        sp_win_PT = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        sp_drawn_PT = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        sp_lost_PT = new javax.swing.JSpinner();
        textf_puan_PT = new javax.swing.JTextField();
        sp_atılan_PT = new javax.swing.JSpinner();
        sp_yenen_PT = new javax.swing.JSpinner();
        textf_averaj_PT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textf_id_PT = new javax.swing.JTextField();
        textf_arama = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        label_ligadı_PT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        puanTablosuPanel.setBackground(new java.awt.Color(205, 242, 206));
        puanTablosuPanel.setForeground(new java.awt.Color(255, 255, 255));

        PuanTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "takım_id", "takım adı", "lig adı", "oynanan", "galibiyet", "beraberlik", "mağlubiyet", "atılan gol", "yenilen gol", "averaj", "puan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PuanTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PuanTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PuanTablosu);

        buton_ekle.setText("Takım Ekle");
        buton_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_ekleActionPerformed(evt);
            }
        });

        buton_güncelle.setText("Güncelle");
        buton_güncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_güncelleActionPerformed(evt);
            }
        });

        buton_sil.setText("Sil");
        buton_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_silActionPerformed(evt);
            }
        });

        tablo_label.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        tablo_label.setText("PUAN TABLOSU");
        tablo_label.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 102), new java.awt.Color(255, 255, 153), null, new java.awt.Color(204, 204, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2)));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel8.setText("Averaj :");

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel3.setText("Galibiyet sayısı : ");

        label_takımadı_PT.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel4.setText("Beraberlik Sayısı :");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel5.setText("Mağlubiyet Sayısı :");

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel6.setText("Attığı gol :");

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel10.setText("TOPLAM PUAN :");

        textf_puan_PT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textf_puan_PTActionPerformed(evt);
            }
        });

        textf_averaj_PT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textf_averaj_PTActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel1.setText("Takım Adı : ");

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel7.setText("Yediği gol :");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel2.setText("Oynadığı maç : ");

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel9.setText("Takım Id :");

        textf_id_PT.setEditable(false);
        textf_id_PT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textf_id_PTActionPerformed(evt);
            }
        });

        textf_arama.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        textf_arama.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 153), java.awt.Color.darkGray));
        textf_arama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textf_aramaActionPerformed(evt);
            }
        });
        textf_arama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textf_aramaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textf_aramaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textf_aramaKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel11.setText("Aramak istediğiniz takımı girin :");

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel12.setText("Lig Adı :");

        label_ligadı_PT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_ligadı_PTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout puanTablosuPanelLayout = new javax.swing.GroupLayout(puanTablosuPanel);
        puanTablosuPanel.setLayout(puanTablosuPanelLayout);
        puanTablosuPanelLayout.setHorizontalGroup(
            puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puanTablosuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(puanTablosuPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(sp_atılan_PT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sp_drawn_PT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, puanTablosuPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sp_win_PT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sp_oynanan_PT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, puanTablosuPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sp_lost_PT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(puanTablosuPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textf_puan_PT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sp_yenen_PT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textf_averaj_PT, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(puanTablosuPanelLayout.createSequentialGroup()
                                    .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(label_takımadı_PT)
                                        .addComponent(textf_id_PT, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                        .addComponent(label_ligadı_PT))))
                            .addComponent(buton_güncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(puanTablosuPanelLayout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(buton_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buton_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                            .addGroup(puanTablosuPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1)
                                .addContainerGap())))
                    .addGroup(puanTablosuPanelLayout.createSequentialGroup()
                        .addComponent(tablo_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(textf_arama, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        puanTablosuPanelLayout.setVerticalGroup(
            puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, puanTablosuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tablo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textf_arama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(puanTablosuPanelLayout.createSequentialGroup()
                        .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textf_id_PT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_takımadı_PT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_ligadı_PT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_oynanan_PT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_win_PT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_drawn_PT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_lost_PT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_atılan_PT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp_yenen_PT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(puanTablosuPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(textf_averaj_PT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textf_puan_PT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(puanTablosuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buton_güncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puanTablosuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puanTablosuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buton_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_ekleActionPerformed
        TakımEkle add_team = new TakımEkle(); //takım ekle sayfası açılır
        add_team.setVisible(true);
        add_team.pack();
        add_team.setLocationRelativeTo(null);
        add_team.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //takım ekleme sayfası kapatıldığında ana ekranın hala açık kalmasını sağlar
    }//GEN-LAST:event_buton_ekleActionPerformed

    
    
    private void textf_averaj_PTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textf_averaj_PTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textf_averaj_PTActionPerformed

    private void textf_puan_PTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textf_puan_PTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textf_puan_PTActionPerformed

    
//güncelleme    
    //takım adı ve oynanan oyun sayıları boşsa 0 değeri dönecek ve ekleme yapılamayacak
    public boolean boşlukKontrol(){
        return !(label_takımadı_PT).getText().equals("") && !(label_ligadı_PT).getText().equals("") && !((Integer)sp_oynanan_PT.getValue()).equals(0) && !(textf_id_PT.getText()).equals(""); 
    }   
    
    //galibiyet beraberlik ve mağlubiyet sayılarının toplamı oynanan oyun sayısını tutmuyorsa da çalışmayacak
    public boolean oyunSayısıKontrol(){
        int toplamOyun = (Integer)sp_win_PT.getValue() + (Integer)sp_drawn_PT.getValue() + (Integer)sp_lost_PT.getValue();
        int kontrol = (Integer) sp_oynanan_PT.getValue();
        return (toplamOyun == kontrol);
        
    }
    
    //sayı değerlerinin pozitif veya 0 olduğunun kontrolünü sağlar
    public boolean sayıDeğeriKontrol(){
        return ((Integer) sp_oynanan_PT.getValue() >= 0 && (Integer)sp_win_PT.getValue()>= 0 && (Integer)sp_drawn_PT.getValue()>= 0 && 
                (Integer)sp_lost_PT.getValue()>= 0 && (Integer) sp_atılan_PT.getValue()>= 0 && (Integer) sp_yenen_PT.getValue()>= 0);
    }
    
    private void buton_güncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_güncelleActionPerformed
        int id = Integer.valueOf(textf_id_PT.getText()); //textfieldden aldığımız için sonrasında inte dönüştürdük
        String takımAdı = label_takımadı_PT.getText();
        String ligAdı = label_ligadı_PT.getText();
        int oynanan =(Integer) sp_oynanan_PT.getValue(); //spinnerdeki değeri aldık
        int win = (Integer)sp_win_PT.getValue();
        int drawn =(Integer) sp_drawn_PT.getValue();
        int lost =(Integer) sp_lost_PT.getValue(); 
        int atılan =(Integer) sp_atılan_PT.getValue();
        int yenen =(Integer) sp_yenen_PT.getValue();
        int lig_id = 0;
       
        
            //averaj için
        int averaj = atılan - yenen;
        textf_averaj_PT.setText(String.valueOf(averaj)); //yazdırmak için stringe çevirdik
        
        //toplam puan için
        int toplamPuan = win * 3 + drawn;
        textf_puan_PT.setText(String.valueOf(toplamPuan));

        if (boşlukKontrol() && oyunSayısıKontrol() && sayıDeğeriKontrol()){ 
        //güncelleme yapılmasını sağlar
        Puanlar tk = new Puanlar();
        tk.EkleGüncelleSilTakım('g', id, takımAdı, ligAdı, oynanan, win, drawn, lost, 
                atılan, yenen, averaj, toplamPuan); //puanlar sınıfındaki ilgili metoda giderek güncelleme yapmayı sağlar.
        }
        else{ //birden çok hata varsa uyarıların hepsinin sırayla alınmasını istedim.
            if(!boşlukKontrol()){          
            JOptionPane.showMessageDialog(null, "takım ismi veya oyun sayısı geçerli değil!");
            }
        
            if (!oyunSayısıKontrol()){ 
            JOptionPane.showMessageDialog(null, "oynanan oyun sayısı ile diğer veriler eşleşmedi!");
            }
            if (!sayıDeğeriKontrol()){
            JOptionPane.showMessageDialog(null, "Girilen sayı değerleri sıfırdan küçük olamaz!");
            }
        }
        //eski tablodan bir tane daha eklemek yerine üstüne ekler
        PuanTablosu.setModel(new DefaultTableModel(null, new Object[] {"takım_id", "takım adı", "lig adı", "oynanan maç", "galibiyet", "beraberlik", "mağlubiyet", "atılan gol", "yenilen gol", "averaj", "toplam puan"}));
        puant.fillPuanTablosu(PuanTablosu, "");
    }//GEN-LAST:event_buton_güncelleActionPerformed

    private void textf_id_PTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textf_id_PTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textf_id_PTActionPerformed

    private void textf_aramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textf_aramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textf_aramaActionPerformed

    
    
    private void textf_aramaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textf_aramaKeyTyped
                
    }//GEN-LAST:event_textf_aramaKeyTyped

    
    private void textf_aramaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textf_aramaKeyPressed
  
    }//GEN-LAST:event_textf_aramaKeyPressed
//puan tablosunda arama yapmamızı sağlar --> keyReleased ile yapmak daha verimli
    private void textf_aramaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textf_aramaKeyReleased
        PuanTablosu.setModel(new DefaultTableModel(null, new Object[] {"takım_id", "takım adı","oynanan maç", "galibiyet", "beraberlik", "mağlubiyet", "atılan gol", "yenilen gol", "averaj", "toplam puan"}));
        puant.fillPuanTablosu(PuanTablosu, textf_arama.getText());
    }//GEN-LAST:event_textf_aramaKeyReleased

    private void buton_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_silActionPerformed
        int id = Integer.parseInt(textf_id_PT.getText());
        Puanlar tk = new Puanlar();
        tk.EkleGüncelleSilTakım('s', id, null, null, null, null, null, null, null, null, null, null);
        
        PuanTablosu.setModel(new DefaultTableModel(null, new Object[] {"takım_id", "takım adı", "lig adı", "oynanan maç", "galibiyet", "beraberlik", "mağlubiyet", "atılan gol", "yenilen gol", "averaj", "toplam puan"}));
        puant.fillPuanTablosu(PuanTablosu, "");
        
        //seçilen satır silindikten sonra sol ekranda bilgileri de silinsin
        textf_id_PT.setText("");
        label_takımadı_PT.setText("");
        label_ligadı_PT.setText("");
        sp_oynanan_PT.setValue(0); //spinnerdeki değeri aldık
        sp_win_PT.setValue(0);
        sp_drawn_PT.setValue(0);
        sp_lost_PT.setValue(0); 
        sp_atılan_PT.setValue(0);
        sp_yenen_PT.setValue(0);
        textf_averaj_PT.setText("");
        textf_puan_PT.setText("");
    }//GEN-LAST:event_buton_silActionPerformed

    //puan tablosunda seçilen değer yanda gözükür. güncelleme ve silme yapmak için
    private void PuanTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PuanTablosuMouseClicked
        int rowIndex = PuanTablosu.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)PuanTablosu.getModel();

        textf_id_PT.setText(model.getValueAt(rowIndex, 0).toString());
        label_takımadı_PT.setText(model.getValueAt(rowIndex, 1).toString());
        label_ligadı_PT.setText(model.getValueAt(rowIndex, 2).toString());
        sp_oynanan_PT.setValue(model.getValueAt(rowIndex, 3));
        sp_win_PT.setValue(model.getValueAt(rowIndex, 4));
        sp_drawn_PT.setValue(model.getValueAt(rowIndex, 5));
        sp_lost_PT.setValue(model.getValueAt(rowIndex, 6));
        sp_atılan_PT.setValue(model.getValueAt(rowIndex, 7));
        sp_yenen_PT.setValue(model.getValueAt(rowIndex, 8));
        textf_averaj_PT.setText(model.getValueAt(rowIndex, 9).toString());
        textf_puan_PT.setText(model.getValueAt(rowIndex, 10).toString());

    }//GEN-LAST:event_PuanTablosuMouseClicked

    private void label_ligadı_PTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_ligadı_PTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_ligadı_PTActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PuanTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PuanTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PuanTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PuanTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PuanTablosu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable PuanTablosu;
    private javax.swing.JButton buton_ekle;
    private javax.swing.JButton buton_güncelle;
    private javax.swing.JButton buton_sil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField label_ligadı_PT;
    private javax.swing.JTextField label_takımadı_PT;
    public javax.swing.JPanel puanTablosuPanel;
    private javax.swing.JSpinner sp_atılan_PT;
    private javax.swing.JSpinner sp_drawn_PT;
    private javax.swing.JSpinner sp_lost_PT;
    private javax.swing.JSpinner sp_oynanan_PT;
    private javax.swing.JSpinner sp_win_PT;
    private javax.swing.JSpinner sp_yenen_PT;
    private javax.swing.JLabel tablo_label;
    private javax.swing.JTextField textf_arama;
    private javax.swing.JTextField textf_averaj_PT;
    private javax.swing.JTextField textf_id_PT;
    private javax.swing.JTextField textf_puan_PT;
    // End of variables declaration//GEN-END:variables
}

